flags:
  semigroups:
    bytestring-builder: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.1.0.0
- attoparsec-0.13.1.0
- base-compat-0.9.1
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- blaze-html-0.8.1.3
- blaze-markup-0.7.1.1
- dlist-0.8.0.2
- exceptions-0.8.3
- extensible-exceptions-0.1.1.4
- fail-4.9.0.0
- happstack-lite-7.3.6
- happstack-server-7.4.6.2
- hashable-1.2.5.0
- hslogger-1.2.10
- html-1.0.1.2
- integer-logarithms-1.0.1
- monad-control-1.0.1.0
- mtl-2.2.1
- network-2.6.3.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.11
- primitive-0.6.2.0
- random-1.1
- scientific-0.3.4.10
- semigroups-0.18.2
- sendfile-0.7.9
- stm-2.4.4.1
- syb-0.6
- system-filepath-0.4.13.4
- tagged-0.8.5
- text-1.2.2.1
- threads-0.5.1.4
- time-compat-0.1.0.3
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.2
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vector-0.12.0.0
- zlib-0.6.1.2
resolver: ghc-7.10.3
